trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core 2.2 SDK'
  inputs:
    packageType: sdk
    version: '2.2.x'

- task: UseDotNet@2
  displayName: 'Use .Net Core 3.0 SDK'
  inputs:
    packageType: sdk
    includePreviewVersions: true
    version: '3.0.x'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud vhatsura'
    organization: 'vhatsura'
    scannerMode: 'MSBuild'
    projectKey: 'serilog-sinks-kafka'
    projectName: 'serilog-sinks-kafka'
    projectVersion: '$(AssemblyVersion)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration)'
    nobuild: true

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    arguments: '--configuration $(buildConfiguration)'
    nobuild: true

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts to Azure Pipelines
  inputs:
    artifactName: 'packages'
